project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks.views import index

urlpatterns = [
    path('', index),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
    path('admin/', admin.site.urls),
]

project_tracker/quality_control/urls.py
from django.urls import include, path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    # path('bugs/', views.bug_report_list, name='bug_report_list'),
    # path('features/', views.feature_list, name='feature_list'),
    # path('bugs/<int:bug_id>/', views.bug_report_detail, name='bug_report_detail'),
    # path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),
    # path('bug/new/', views.create_bug_report, name='create_bug_report'),
    # path('feature/new/', views.create_feature_request, name='create_feature_request'),
    # path('bug/<int:bug_id>/update/', views.update_bug, name='update_bug'),
    # path('feature/<int:feature_id>/update/', views.update_feature, name='update_feature'),
    # path('bug/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    # path('feature/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),

    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.BugReportListView.as_view(), name='bug_report_list'),
    path('features/', views.FeatureRequestListView.as_view(), name='feature_list'),
    path('bugs/<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_report_detail'),
    path('features/<int:feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_detail'),
    path('bug/create/', views.BugReportCreateView.as_view(), name='create_bug_report'),
    path('feature/create/', views.FeatureRequestCreateView.as_view(), name='create_feature_request'),
    path('bug/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bug'),
    path('feature/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_feature'),
    path('bug/<int:bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bug'),
    path('feature/<int:feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_feature'),

]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [

    # path('', views.index, name='index'),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    # path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    # path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    # path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    # path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In progress', 'В работе'),
        ('Completed', 'Завершена')
    ]
    PRIORITY_CHOICES = [
        (1, 'Низкий'),
        (2, 'Ниже среднего'),
        (3, 'Средний'),
        (4, 'Выше среднего'),
        (5, 'Высокий')
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='bug_reports',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='bug_reports',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New'
    )
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено')
    ]
    PRIORITY_CHOICES = [
        (1, 'Низкий'),
        (2, 'Ниже среднего'),
        (3, 'Средний'),
        (4, 'Выше среднего'),
        (5, 'Высокий')
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='feature_requests',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='feature_requests',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Review'
    )
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest

class BugReportForm(forms.ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

class FeatureRequestForm(forms.ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.views import View
from tasks.models import Project, Task
from quality_control.models import BugReport, FeatureRequest
from django.shortcuts import render, get_object_or_404, redirect

def index(request):
    return render(request,'quality_control/index.html')
# def index(request):
#     bugs_url = reverse('quality_control:bug_report_list')
#     features_url = reverse('quality_control:feature_list')
#     html = f"<h1>Система контроля качества</h1>"
#     html += f"<a href='{bugs_url}'>Список всех багов</a>"
#     html += f"<br><a href='{features_url}'>Запросы на улучшение</a>"
#     return HttpResponse(html)

def bug_report_list(request):
    bug_report_list = BugReport.objects.all()
    return render(request, 'quality_control/bug_report_list.html', {'bug_report_list': bug_report_list})

# def bug_report_list(request):
#     bug_reports = BugReport.objects.all()
#     html = '<h1>Список всех Багов</h1>'
#     for bug_report in bug_reports:
#         html += f'<li><a href="{bug_report.id}/">{bug_report.title}</a></li>'
#     return HttpResponse(html)
def bug_report_detail(request, bug_id):
    bug_reports = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_report_detail.html', {'bug_report_list': bug_reports})

from django.shortcuts import redirect
from .forms import BugReportForm

def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_report_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_create.html', {'form': form})

# def bug_report_detail(request, bug_id):
#     bug_report = get_object_or_404(BugReport, id=bug_id)
#     response_html = f'<h1>{bug_report.title}</h1>'
#     response_html += f'<p>Status: {bug_report.status}</p>'
#     response_html += f'<p>Description: {bug_report.description}</p>'
#     return HttpResponse(response_html)

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features': features})

# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     html = '<h1>Список всех Запросов на улучшение</h1>'
#     for feature in features:
#         html += f'<li><a href="{feature.id}/">{feature.title}</a></li>'
#     return HttpResponse(html)

def feature_detail(request, feature_id):
    features = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'features': features})

# def feature_detail(request, feature_id):
#     feature = get_object_or_404(FeatureRequest, id=feature_id)
#     response_html = f'<h1>{feature.title}</h1>'
#     response_html += f'<p>Status: {feature.status}</p>'
#     response_html += f'<p>Priority: {feature.priority}</p>'
#     response_html += f'<p>Description: {feature.description}</p>'
#     return HttpResponse(response_html)

#def quality_control_index(request):
#    return HttpResponse("<h1>Главная страница приложения quality_control</h1>")
from .forms import FeatureRequestForm
def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_create.html', {'form': form})

def update_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_report_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})

def update_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'features': feature})

def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bug_report_list')

def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list', feature_id=feature_id)

from django.views import View

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#
#         bugs_url = reverse('quality_control:bug_report_list')
#         features_url = reverse('quality_control:feature_list')
#         html = f"<h1>Система контроля качества</h1>"
#         html += f"<a href='{bugs_url}'>Список всех багов</a>"
#         html += f"<br><a href='{features_url}'>Запросы на улучшение</a>"
#         return HttpResponse(html)

from django.views.generic import ListView

class BugReportListView(ListView):

    model = BugReport
    template_name = 'quality_control/bug_report_list.html'
    context_object_name = 'bug_report_list'


# class BugReportListView(ListView):
#
#     model = BugReport
#
#     def get(self, request, *args, **kwargs):
#         bug_reports = self.get_queryset()
#         bug_reports_html = '<h1>Список багов</h1>'
#
#         for bug_report in bug_reports:
#             bug_reports_html += f'<li><a href="{bug_report.id}/">{bug_report.title}</a></li>'
#
#         bug_reports_html += '</ul>'
#
#         # Возвращаем HTML-код как HttpResponse
#         return HttpResponse(bug_reports_html)


from django.views.generic import DetailView

class BugReportDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_report_detail.html'
    context_object_name = 'bug_report_list'

# class BugReportDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug_report = self.object
#         response_html = f'<h1>{bug_report.title}</h1>'
#         response_html += f'<p>Status: {bug_report.status}</p>'
#         response_html += f'<p>Description: {bug_report.description}</p>'
#         response_html += f'<p>Project: {bug_report.project.name}</p>'
#         response_html += f'<p>Task: {bug_report.task.name}</p>'
#         return HttpResponse(response_html)


class FeatureRequestListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'
    context_object_name = 'features'
# class FeatureRequestListView(ListView):
#     model = FeatureRequest
#
#     def get(self, request, *args, **kwargs):
#         features = self.get_queryset()
#         features_html = '<h1>Список багов</h1>'
#
#         features_html = '<h1>Список всех Запросов на улучшение</h1>'
#         for feature in features:
#             features_html += f'<li><a href="{feature.id}/">{feature.title}</a></li>'
#         return HttpResponse(features_html)
class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = 'features'
    template_name = 'quality_control/feature_detail.html'


# class FeatureRequestDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         feature = self.object
#         response_html = f'<h1>{feature.title}</h1>'
#         response_html += f'<p>Status: {feature.status}</p>'
#         response_html += f'<p>Priority: {feature.priority}</p>'
#         response_html += f'<p>Description: {feature.description}</p>'
#         response_html += f'<p>Project: {feature.project.name}</p>'
#         response_html += f'<p>Task: {feature.task.name}</p>'
#         return HttpResponse(response_html)

from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy

class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_create.html'
    success_url = reverse_lazy('quality_control:bug_report_list')


from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy

class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_create.html'
    success_url = reverse_lazy('quality_control:feature_list')

from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_report_list')

class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')

from django.views.generic.edit import DeleteView

class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = 'bug_report_list'

project_tracker/quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление проекта</h1>
    <p>Вы уверены, что хотите удалить проект "{{ bug_report_list.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bug_report_list.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_report_detail' bug_report_list.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_create.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый BugReport</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ bug_report_list.title }}</h1>
    <p>Описание: {{ bug_report_list.description }}</p>
    <p>Приоритет: {{ bug_report_list.priority }}</p>

    <p><a href="{% url 'quality_control:update_bug' bug_report_list.id %}">Изменить баг</a></p>
    <p><a href="{% url 'quality_control:delete_bug' bug_report_list.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот баг?');">Удалить баг</a></p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список багов</h1>




    <p><a href="{% url 'quality_control:create_bug_report' %}">Создать новый bugreport</a></p>

    <ul>
        {% for bug_report in bug_report_list %}
            <li><a href="{% url 'quality_control:bug_report_detail' bug_report.id %}">{{ bug_report.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение бага: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление проекта</h1>
    <p>Вы уверены, что хотите удалить проект "{{ features.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' features.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' features.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_create.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый FeatureRequest</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ features.title }}</h1>



    <p>Статус: {{ features.status }}</p>
    <p>Приоритет: {{ features.priority }}</p>
    <p>Описание: {{ features.description }}</p>

    <p><a href="{% url 'quality_control:update_feature' features.id %}">Изменить запрос на улучшение</a></p>

    <p><a href="{% url 'quality_control:delete_feature' features.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список всех запросов на улучшение</h1>

    <p><a href="{% url 'quality_control:create_feature_request' %}">Создать новый FeatureRequest</a></p>

    <ul>
        {% for feature in features %}
            <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ features.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Система контроля качества</h1>
    <a href="{% url 'quality_control:bug_report_list' %}">Список всех багов</a>
    <br><a href="{% url 'quality_control:feature_list' %}">Список всех запросов на улучшение</a>

{% endblock %}